name: sahashop_customer
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0-nullsafety.0
  bubble: ^1.2.1
  badges: ^3.1.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  carousel_slider: ^5.0.0
  comment_tree: ^0.3.0
  connectivity_plus: ^6.0.5  #cloud_firestore: ^3.1.18
  custom_timer: ^0.2.3
  dio: ^5.0.0
  device_info: ^2.0.0
  empty_widget: ^0.0.1
  expandable: ^5.0.1
  multi_image_picker2: ^5.0.0
  marquee_widget: ^1.2.0
  flash: ^3.0.5+1
  font_awesome_flutter: ^10.1.0
  firebase_messaging: ^14.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_datetime_picker_plus: ^2.0.1
  flutter_slidable: ^3.1.1
  flutter_speed_dial: ^7.0.0
  flutter_chat_types: ^3.0.0
  flutter_linkify: ^6.0.0
  fluttertoast: ^8.2.8
  flutter_rating_bar: ^4.0.1
  flutter_colorpicker: ^1.0.3
  flutter_barcode_scanner: ^2.0.0
  flutter_chat_ui: ^1.6.9
  flutter_cache_manager: ^3.3.0

  flutter_inappwebview: ^6.0.0

  
  http_parser: ^4.0.0
  html: ^0.15.2
  get: ^4.6.1
  google_fonts: 4.0.4
  gallery_saver: ^2.3.2
  screenshot: ^3.0.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.5
  socket_io_client: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_charts: ^26.2.9
  syncfusion_flutter_datepicker: ^26.2.9
  
  shimmer: ^3.0.0
  switcher_button: ^0.0.3
  sticky_headers: ^0.3.0+2
  share_plus: ^10.0.2
  page_indicator: ^0.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  ionicons: ^0.2.1
  image_cropper: ^4.0.1
  image: ^4.0.16
  image_gallery_saver: ^2.0.3
  qr_code_scanner: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.2
  pin_code_fields: ^8.0.1
  path_provider: ^2.0.1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.15.0
  package_info: ^2.0.2
  retrofit: ^4.0.1
  readmore: ^3.0.0
  url_launcher: ^6.0.4
  youtube_player_flutter: ^9.0.3
  version_check: ^0.4.0
  flutter_fortune_wheel: ^1.3.0
  shake: ^2.2.0
  card_swiper: ^3.0.1
  after_layout: ^1.2.0
  barcode_widget: ^2.0.3
  flutter_html: ^3.0.0-alpha.6
  flutter_widget_from_html: ^0.14.11
  webview_flutter: ^4.0.7
  chewie: ^1.4.0
  video_player: ^2.6.1
  video_compress: ^3.1.2
  qr_flutter: ^4.1.0
  android_intent_plus: ^5.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  appsflyer_sdk: ^6.12.2

dev_dependencies:
  retrofit_generator: ^8.2.0
  build_runner: ^2.4.6
  change_app_package_name: ^1.0.0

  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.saha.example.sahashop_customer
        pluginClass: SahashopCustomerPlugin
      ios:
        pluginClass: SahashopCustomerPlugin

  assets:
    - assets/
    - assets/images/
    - assets/community/
    - assets/icons/
    - assets/svg/
    - assets/style_7/
    - assets/saha_loading.png
    - assets/style1/
    - assets/app_user/svg/home/
    - assets/app_customer/home_button/
    - assets/app_user/svg/config/
    - assets/image_default/

  fonts:
    - family: baloo2
      fonts:
        - asset: assets/fonts/baloo2/baloo2.ttf